language: python
cache: pip
python: 2.7.10
before_install:
  - 'sudo apt-get update && sudo apt-get install --yes unoconv libreoffice'
install:
  - 'pip install -r requirements.txt'
  # `awscli` is required for invalidation of CloudFront distributions.
  - 'pip install awscli'
script:
  - 'make -C content/press'
  - 'python main.py -d'
after_success:
  - 'chmod u+x compress.sh && ./compress.sh'
  - file output/blogs.html
  - cat output/blogs.html
deploy:
  -
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: www.initc3.org
    region: us-east-1
    skip_cleanup: true
    default_text_charset: utf-8
    # Set the Cache-Control header.
    cache_control: max-age=43200
    local-dir: output
    detect_encoding: true
    on:
      branch: master
after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
notifications:
  email:
    recipients:
      - admin@initc3.org
    on_failure: always
    on_success: always
